// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Npmlog = require("npmlog");
var Process = require("process");
var Js_option = require("bs-platform/lib/js/js_option.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var EosBp_Fetch$ReactTemplate = require("../src/EosBp_Fetch.js");

((global.XMLHttpRequest = require('xhr2').XMLHttpRequest));

((process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'));

var httpEndpoint = "http://node2.liquideos.com";

function handleRow(row) {
  return EosBp_Fetch$ReactTemplate.bpJsonRaw(row, undefined, /* () */0).then((function (result) {
                var label = "fetch bp.json";
                var metadata = function (url, xhr) {
                  return {
                          producer: row[/* owner */0],
                          row_url: row[/* url */4],
                          request_url: url,
                          response_url: Js_primitive.nullable_to_opt(xhr.responseURL),
                          response_type: Js_primitive.nullable_to_opt(xhr.getResponseHeader("Content-Type"))
                        };
                };
                switch (result.tag | 0) {
                  case 0 : 
                      Npmlog.info(label, "Valid JSON4", metadata(result[0], result[1]));
                      return Promise.resolve(Js_primitive.some(result[2]));
                  case 1 : 
                      Npmlog.warn(label, "Valid JSON5", metadata(result[0], result[1]));
                      return Promise.resolve(Js_primitive.some(result[2]));
                  case 2 : 
                      Npmlog.error(label, "Invalid JSON", metadata(result[0], result[1]));
                      return Promise.resolve(undefined);
                  case 3 : 
                      Npmlog.error(label, "Bad response", metadata(result[0], result[1]));
                      return Promise.resolve(undefined);
                  case 4 : 
                      Npmlog.error(label, "Bad URL", {
                            producer: row[/* owner */0],
                            url: result[0]
                          });
                      return Promise.resolve(undefined);
                  case 5 : 
                      Npmlog.error(label, "Timed out", metadata(result[0], result[1]));
                      return Promise.resolve(undefined);
                  case 6 : 
                      Npmlog.error(label, "Unreachable", metadata(result[0], result[1]));
                      return Promise.resolve(undefined);
                  case 7 : 
                      Npmlog.error(label, "Unknown error", {
                            producer: row[/* owner */0],
                            url: result[0],
                            error: result[1]
                          });
                      return Promise.resolve(undefined);
                  
                }
              }));
}

EosBp_Fetch$ReactTemplate.tableRows(httpEndpoint, undefined, /* () */0).then((function (response) {
          var rows = Js_option.getWithDefault(/* array */[], EosBp_Fetch$ReactTemplate.Response[/* getData */2](response));
          console.log("got table rows", rows.length);
          return Promise.all(rows.map(handleRow));
        })).then((function () {
        Npmlog.info("", "Done", "");
        Process.exit(0);
        return Promise.resolve(/* () */0);
      }));

var Log = 0;

exports.Log = Log;
exports.httpEndpoint = httpEndpoint;
exports.handleRow = handleRow;
/*  Not a pure module */
