// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Ajv = require("ajv");
var Js_list = require("bs-platform/lib/js/js_list.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Js_option = require("bs-platform/lib/js/js_option.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var SchemaJson = require("bp-info-standard/schema.json");

function decode(j) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, j),
          /* country */Json_decode.field("country", Json_decode.string, j),
          /* latitude */Json_decode.field("latitude", Json_decode.$$float, j),
          /* longitude */Json_decode.field("longitude", Json_decode.$$float, j)
        ];
}

function encode(d) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "name",
                d[/* name */0]
              ],
              /* :: */[
                /* tuple */[
                  "country",
                  d[/* country */1]
                ],
                /* :: */[
                  /* tuple */[
                    "latitude",
                    d[/* latitude */2]
                  ],
                  /* :: */[
                    /* tuple */[
                      "longitude",
                      d[/* longitude */3]
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

var Location = /* module */[
  /* decode */decode,
  /* encode */encode
];

function encodeObjectWithOptions(fields) {
  return Json_encode.object_(Belt_List.fromArray(Js_list.foldLeft((function (fields, field) {
                        if (field !== undefined) {
                          fields.push(field);
                        }
                        return fields;
                      }), /* array */[], fields)));
}

function decode$1(j) {
  var partial_arg = Json_decode.either((function (param) {
          return Json_decode.array(Json_decode.string, param);
        }), (function (param) {
          return Json_decode.map((function (s) {
                        return /* array */[s];
                      }), Json_decode.string, param);
        }));
  return /* record */[
          /* location */Json_decode.field("location", decode, j),
          /* isProducer */Json_decode.optional((function (param) {
                  return Json_decode.field("is_producer", Json_decode.bool, param);
                }), j),
          /* nodeType */Json_decode.optional((function (param) {
                  return Json_decode.field("node_type", partial_arg, param);
                }), j),
          /* p2pEndpoint */Json_decode.optional((function (param) {
                  return Json_decode.field("p2p_endpoint", Json_decode.string, param);
                }), j),
          /* bnetEndpoint */Json_decode.optional((function (param) {
                  return Json_decode.field("bnet_endpoint", Json_decode.string, param);
                }), j),
          /* apiEndpoint */Json_decode.optional((function (param) {
                  return Json_decode.field("api_endpoint", Json_decode.string, param);
                }), j),
          /* sslEndpoint */Json_decode.optional((function (param) {
                  return Json_decode.field("ssl_endpoint", Json_decode.string, param);
                }), j)
        ];
}

function encode$1(d) {
  return encodeObjectWithOptions(/* :: */[
              /* tuple */[
                "location",
                encode(d[/* location */0])
              ],
              /* :: */[
                Js_option.map((function (x) {
                        return /* tuple */[
                                "is_producer",
                                x
                              ];
                      }), d[/* isProducer */1]),
                /* :: */[
                  Js_option.map((function (x) {
                          return /* tuple */[
                                  "node_type",
                                  x
                                ];
                        }), d[/* nodeType */2]),
                  /* :: */[
                    Js_option.map((function (x) {
                            return /* tuple */[
                                    "p2p_endpoint",
                                    x
                                  ];
                          }), d[/* p2pEndpoint */3]),
                    /* :: */[
                      Js_option.map((function (x) {
                              return /* tuple */[
                                      "bnet_endpoint",
                                      x
                                    ];
                            }), d[/* bnetEndpoint */4]),
                      /* :: */[
                        Js_option.map((function (x) {
                                return /* tuple */[
                                        "api_endpoint",
                                        x
                                      ];
                              }), d[/* apiEndpoint */5]),
                        /* :: */[
                          Js_option.map((function (x) {
                                  return /* tuple */[
                                          "ssl_endpoint",
                                          x
                                        ];
                                }), d[/* sslEndpoint */6]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var Node = /* module */[
  /* decode */decode$1,
  /* encode */encode$1
];

function decode$2(j) {
  return /* record */[
          /* logo256 */Json_decode.optional((function (param) {
                  return Json_decode.field("logo_256", Json_decode.string, param);
                }), j),
          /* logo1024 */Json_decode.optional((function (param) {
                  return Json_decode.field("logo_1024", Json_decode.string, param);
                }), j),
          /* logoSvg */Json_decode.optional((function (param) {
                  return Json_decode.field("logo_svg", Json_decode.string, param);
                }), j)
        ];
}

function encode$2(d) {
  return encodeObjectWithOptions(/* :: */[
              Js_option.map((function (x) {
                      return /* tuple */[
                              "logo_256",
                              x
                            ];
                    }), d[/* logo256 */0]),
              /* :: */[
                Js_option.map((function (x) {
                        return /* tuple */[
                                "logo_1024",
                                x
                              ];
                      }), d[/* logo1024 */1]),
                /* :: */[
                  Js_option.map((function (x) {
                          return /* tuple */[
                                  "logo_svg",
                                  x
                                ];
                        }), d[/* logoSvg */2]),
                  /* [] */0
                ]
              ]
            ]);
}

var Branding = /* module */[
  /* decode */decode$2,
  /* encode */encode$2
];

function decode$3(j) {
  return /* record */[
          /* facebook */Json_decode.optional((function (param) {
                  return Json_decode.field("facebook", Json_decode.string, param);
                }), j),
          /* github */Json_decode.optional((function (param) {
                  return Json_decode.field("github", Json_decode.string, param);
                }), j),
          /* keybase */Json_decode.optional((function (param) {
                  return Json_decode.field("keybase", Json_decode.string, param);
                }), j),
          /* reddit */Json_decode.optional((function (param) {
                  return Json_decode.field("reddit", Json_decode.string, param);
                }), j),
          /* steemit */Json_decode.optional((function (param) {
                  return Json_decode.field("steemit", Json_decode.string, param);
                }), j),
          /* telegram */Json_decode.optional((function (param) {
                  return Json_decode.field("telegram", Json_decode.string, param);
                }), j),
          /* twitter */Json_decode.optional((function (param) {
                  return Json_decode.field("twitter", Json_decode.string, param);
                }), j),
          /* wechat */Json_decode.optional((function (param) {
                  return Json_decode.field("wechat", Json_decode.string, param);
                }), j),
          /* youtube */Json_decode.optional((function (param) {
                  return Json_decode.field("youtube", Json_decode.string, param);
                }), j)
        ];
}

function encode$3(d) {
  return encodeObjectWithOptions(/* :: */[
              Js_option.map((function (x) {
                      return /* tuple */[
                              "facebook",
                              x
                            ];
                    }), d[/* facebook */0]),
              /* :: */[
                Js_option.map((function (x) {
                        return /* tuple */[
                                "github",
                                x
                              ];
                      }), d[/* github */1]),
                /* :: */[
                  Js_option.map((function (x) {
                          return /* tuple */[
                                  "keybase",
                                  x
                                ];
                        }), d[/* keybase */2]),
                  /* :: */[
                    Js_option.map((function (x) {
                            return /* tuple */[
                                    "reddit",
                                    x
                                  ];
                          }), d[/* reddit */3]),
                    /* :: */[
                      Js_option.map((function (x) {
                              return /* tuple */[
                                      "steemit",
                                      x
                                    ];
                            }), d[/* steemit */4]),
                      /* :: */[
                        Js_option.map((function (x) {
                                return /* tuple */[
                                        "telegram",
                                        x
                                      ];
                              }), d[/* telegram */5]),
                        /* :: */[
                          Js_option.map((function (x) {
                                  return /* tuple */[
                                          "twitter",
                                          x
                                        ];
                                }), d[/* twitter */6]),
                          /* :: */[
                            Js_option.map((function (x) {
                                    return /* tuple */[
                                            "wechat",
                                            x
                                          ];
                                  }), d[/* wechat */7]),
                            /* :: */[
                              Js_option.map((function (x) {
                                      return /* tuple */[
                                              "youtube",
                                              x
                                            ];
                                    }), d[/* youtube */8]),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var Social = /* module */[
  /* decode */decode$3,
  /* encode */encode$3
];

function decode$4(j) {
  return /* record */[
          /* candidateName */Json_decode.field("candidate_name", Json_decode.string, j),
          /* location */Json_decode.field("location", decode, j),
          /* website */Json_decode.field("website", Json_decode.string, j),
          /* codeOfConduct */Json_decode.optional((function (param) {
                  return Json_decode.field("code_of_conduct", Json_decode.string, param);
                }), j),
          /* ownershipDisclosure */Json_decode.optional((function (param) {
                  return Json_decode.field("ownership_disclosure", Json_decode.string, param);
                }), j),
          /* email */Json_decode.optional((function (param) {
                  return Json_decode.field("email", Json_decode.string, param);
                }), j),
          /* branding */Json_decode.optional((function (param) {
                  return Json_decode.field("branding", decode$2, param);
                }), j),
          /* social */Json_decode.optional((function (param) {
                  return Json_decode.field("social", decode$3, param);
                }), j)
        ];
}

function encode$4(d) {
  return encodeObjectWithOptions(/* :: */[
              /* tuple */[
                "candidate_name",
                d[/* candidateName */0]
              ],
              /* :: */[
                /* tuple */[
                  "location",
                  encode(d[/* location */1])
                ],
                /* :: */[
                  /* tuple */[
                    "website",
                    d[/* website */2]
                  ],
                  /* :: */[
                    Js_option.map((function (x) {
                            return /* tuple */[
                                    "code_of_conduct",
                                    x
                                  ];
                          }), d[/* codeOfConduct */3]),
                    /* :: */[
                      Js_option.map((function (x) {
                              return /* tuple */[
                                      "ownership_disclosure",
                                      x
                                    ];
                            }), d[/* ownershipDisclosure */4]),
                      /* :: */[
                        Js_option.map((function (x) {
                                return /* tuple */[
                                        "email",
                                        x
                                      ];
                              }), d[/* email */5]),
                        /* :: */[
                          Js_option.map((function (x) {
                                  return /* tuple */[
                                          "branding",
                                          encode$2(x)
                                        ];
                                }), d[/* branding */6]),
                          /* :: */[
                            Js_option.map((function (x) {
                                    return /* tuple */[
                                            "social",
                                            encode$3(x)
                                          ];
                                  }), d[/* social */7]),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var Org = /* module */[
  /* Branding */Branding,
  /* Social */Social,
  /* decode */decode$4,
  /* encode */encode$4
];

function decode$5(j) {
  return /* record */[
          /* producerAccountName */Json_decode.field("producer_account_name", Json_decode.string, j),
          /* producerPublicKey */Json_decode.field("producer_public_key", Json_decode.string, j),
          /* org */Json_decode.field("org", decode$4, j),
          /* nodes */Json_decode.field("nodes", (function (param) {
                  return Json_decode.array(decode$1, param);
                }), j)
        ];
}

function encode$5(d) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "producer_account_name",
                d[/* producerAccountName */0]
              ],
              /* :: */[
                /* tuple */[
                  "producer_public_key",
                  d[/* producerPublicKey */1]
                ],
                /* :: */[
                  /* tuple */[
                    "org",
                    encode$4(d[/* org */2])
                  ],
                  /* :: */[
                    /* tuple */[
                      "nodes",
                      Json_encode.array(encode$1, d[/* nodes */3])
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

var Ajv$1 = /* module */[];

function validate(json) {
  var ajv = new Ajv({
        allErrors: true
      });
  ajv.validate(SchemaJson, json);
  return ajv.errors;
}

function getUrl(baseUrl) {
  var url = baseUrl.replace((/^[^\x00-\x7F]/g), "").replace((/[^\x00-\x7F]$/g), "").replace((/\/$/g), "");
  var match = url.startsWith("http") || url.startsWith("https");
  var url$1 = match ? url : "http://" + url;
  var match$1 = url$1.endsWith(".json");
  if (match$1) {
    return url$1;
  } else {
    return url$1 + "/bp.json";
  }
}

exports.Location = Location;
exports.encodeObjectWithOptions = encodeObjectWithOptions;
exports.Node = Node;
exports.Org = Org;
exports.decode = decode$5;
exports.encode = encode$5;
exports.Ajv = Ajv$1;
exports.validate = validate;
exports.getUrl = getUrl;
/* ajv Not a pure module */
