// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';


var Fetch = 0;

var Json = 0;

var Table = 0;

exports.Fetch = Fetch;
exports.Json = Json;
exports.Table = Table;
/* No side effect */
