// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$ReactTemplate = require("./App.js");

ReactDOMRe.hydrateToElementWithId(ReasonReact.element(undefined, undefined, App$ReactTemplate.make(undefined, /* array */[])), "app");

ReasonReact.Router[/* push */0]("");

/*  Not a pure module */
