// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Eos = require("@sagan-software/bs-eos/src/Eos.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$ReactTemplate = require("./App.js");

ReactDOMRe.hydrateToElementWithId(ReasonReact.element(undefined, undefined, App$ReactTemplate.make(undefined, /* array */[])), "app");

ReasonReact.Router[/* push */0]("");

var eos = Eos.make("http://node2.liquideos.com", undefined, undefined, undefined, undefined, undefined, undefined, /* () */0);

((window.eos = eos));

((window.Eos = require('eosjs')));

exports.eos = eos;
/*  Not a pure module */
