// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Eosjs = require("eosjs");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$ReactTemplate = require("./App.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ReactTemplate.make(/* array */[])), "app");

ReasonReact.Router[/* push */0]("");

var eos = Eosjs({
      httpEndpoint: "http://node2.liquideos.com"
    });

((window.eos = eos));

((window.Eos = require('eosjs')));

exports.eos = eos;
/*  Not a pure module */
